### PR TITLE
Fixed grammar and markdown link

### PR DESCRIPTION
**Pull request by xchopin**
Quick edit in order to fix some typos.

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Thanks but some of what you corrected is not compliant with what I wanted to say, so I can't accept your pull request, but I will use it to do the corrections.

**Comment by xchopin** [comment]
Ok, for which sentence it got wrong ?

**Comment by ImagicTheCat** [comment]
Things like "slots got empty", they are instead  "released", as the free of malloc. Sometimes grammar is not enough in the computer world.

**Comment by xchopin** [comment]
Ah yes my bad I thought about malloc too is 'clear' ok?

**Pull request closed without merging**
