### PR TITLE
Added Romanian Language

### PR DESCRIPTION
**Pull request by antonioganea**
I love this FiveM resource, and I decided to help. Hope you would add this. I worked a lot on it.

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Of course, that's why the language API is here for. If you can, try to keep it updated with the changes of `en.lua` from time to time.

**Comment by antonioganea** [comment]
Sure dude. I really love your work. Problem is : Romanian servers use your resources in commercial ways.... I think it's rather sad that you work on such cool stuff and someone else just has it for free, gets money for running servers and you don't get anything from that. 

    În Miercuri, 10 Ianuarie 2018 18:27:18, Imagic <notifications@github.com> a scris:
 

 Of course, that's why the language API is here for. If you can, try to keep it updated with the changes of en.lua from time to time.—

**Comment by antonioganea** [comment]
Couldn't find any contact information yet. Can you give me your discord or something?

**Comment by ImagicTheCat** [comment]
vRP is released under the MIT license, which allow to do commercial use. In this case the problem would be around FiveM I think.
We do need money to eat (in this society), so I have a Patreon if people want to support me for my work on vRP, but that's it.

Use the FiveM forum private messages if you want to contact me, I don't usually answer to private messages on Discord.

**Pull request merged**
