### PR TITLE
fix weapons loss

### PR DESCRIPTION
**Pull request by SnaiCrys**

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
What weapons loss ? In what scenario weapon names are in lower case ?

**Comment by SnaiCrys** [comment]
string.upper is used if the name of the weapon is accidentally written in lowercase, because of this, weapon is not stored in the database.
`weapons[v] = weapon` string moved to the end because variable is always empty, whatever code is executed below.

**Comment by ImagicTheCat** [comment]
`weapon` is correctly filled, this is how Lua works, unless NeoLua is breaking something, it shouldn't because weapon saving is already working. Your problem is only about upper/lower case. Also, weapons name are hard coded, so I don't know how they can be in lower case. Did you modify the base files ?

**Comment by SnaiCrys** [comment]
no longer relevant

**Pull request closed without merging**
