### PR TITLE
add tasks/scenario menu

### PR DESCRIPTION
**Pull request by SnaiCrys**
-- start anim task
tvRP.playTask(name, anim)
-- stop anim task
tvRP.stopTask()

### CODE REVIEW

**Comment by SnaiCrys** [comment]
I think that these scenarios can be used in different jobs. That is, it adds to the configuration of the transformer possible scenarios.

**Comment by ImagicTheCat** [comment]
What is exactly a task ? A collection of animations managed by the engine ? Do you have a list somewhere ?
I don't think it's a good idea to have a task menu, they should be integrated to the emote menu somehow. It's a good basis, but it needs integration.

**Comment by SnaiCrys** [comment]
These are not simple animations. For example, it's smoking cigarettes, taking pictures with a phone, digging with a shovel.

**Comment by ImagicTheCat** [comment]
What is the difference between in place or at position ?

**Comment by SnaiCrys** [comment]
TaskStartScenarioInPlace
Plays a scenario on a Ped at their current location.

TaskStartScenarioAtPosition
Plays a scenario on a Ped at "custom" position.

https://cdn.rage.mp/public/natives/

**Comment by ImagicTheCat** [comment]
So, why did you set a sitchair check ? The at position doesn't work with it ?

**Comment by SnaiCrys** [comment]
Because he sits in the air. For this I have to reduce the height z. To sit down, you need to stand on a chair.
https://image.prntscr.com/image/f642e6c3ccf34d90883240368013dc04.jpeg

**Comment by ImagicTheCat** [comment]
The task is smart to understand where to do the animation or is it just a trick from you ? (ex: some chair will be shifted).

**Comment by SnaiCrys** [comment]
Some scenarios find the best position. For example, as in the screenshot, the model moves some time until it stops back.
https://pp.userapi.com/c836722/v836722322/438cc/puBVnQj2M88.jpg

**Comment by ImagicTheCat** [comment]
Okay, very nice. I have an idea to easily add this feature to what already exists, so it's pointless to accept the pull request, do you want to be credited in a comment ?

**Comment by SnaiCrys** [comment]
Ok. The reference is not critical for me.

**Comment by ImagicTheCat** [comment]
Ok, will push this in a few minutes.

**Pull request closed without merging**
