### PR TITLE
Update to new version

### PR DESCRIPTION
**Pull request by Santagain**

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Hi, thanks for the update. 

* The version is not really `2.0` since there are no fixed releases for latest vRP versions (so maybe `2.x` or `master` if possible).
* I don't see the `author` field in the doc. It's syntatic sugar for `author("...")`, probably not a good idea to use it.

**Comment by Santagain** [comment]
"Author/name/version/desc" is only aesthetic, to supply other APIs like the list of resources of the CFR.re panel, i will edit to only nescessary infos

**Comment by ImagicTheCat** [comment]
Can you rebase/cleanup ?

**Comment by Santagain** [comment]
do you want me to return the information ("Author/name/version") ?

**Comment by ImagicTheCat** [comment]
No, just to cleanup the commits since they are not "public" yet. "Rebase" is about rewriting the commit history. You can do this interactively with `git rebase -i`.

**Pull request closed without merging**
