### PR TITLE
Multiple Characters option

### PR DESCRIPTION
**Pull request by Neidraidd**
Added a permissions to allow group to access characters menu.
  - Only removes menu item so any characters remain in database.

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Why not https://github.com/ImagicTheCat/vRP/blob/master/vrp/cfg/base.lua#L26 ?

**Comment by Neidraidd** [comment]
This does not remove the option from the menu system. E.g. base.lua configured as 1 but still have the [Characters] menu item.

**Comment by Neidraidd** [comment]
Is there something additional required to get this merged?

**Comment by ImagicTheCat** [comment]
I will add that feature when I will commit things soon (ex: `multi.characters` is not a good name).

**Pull request closed without merging**
