### PR TITLE
Fixed vehicle network id issues by removing mission entity registrati…

### PR DESCRIPTION
**Pull request by dexslab**
…on adding proper manifest version and setting up vehicle migration from config

### CODE REVIEW

**Comment by chaixshot** [comment]
Work?

**Comment by dexslab** [comment]
Yes it should allow proper migration of network ids to allow other scripts to control it please test and see but this similar code worked just fine on esx

**Comment by SnaiCrys** [comment]
Problem with car despawn if there are no nearby players fixed?

**Comment by dexslab** [comment]
if the car is despawning its not properly set to owned by player

**Comment by SnaiCrys** [comment]
Previously, this was due to problems with the id.

**Comment by dexslab** [comment]
Well this fixes the vehicle not properly registering with a network id and allows other scripts to take control of networkid and vehicle. This will make it work properly with the new release of ELS Plus

**Comment by ImagicTheCat** [comment]
What about the FiveM network id changes ? https://forum.fivem.net/t/fivem-update-march-15th-2018/91151  I want to understand everything about this before doing any modifications.

**Comment by dexslab** [comment]
This should not affect that it just revamps your code to allow proper migration of network ids to other scripts that are not directly being used by vRP

**Pull request closed without merging**
