### PR TITLE
added .editorconfig

### PR DESCRIPTION
**Pull request by mbarzda**
Added `.editorconfig` for the basic common code style support.

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
I don't understand, is it about a text editor ?

**Comment by mbarzda** [comment]
yup, it set default settings for the specific project. A lot of open source projects use .editorconfig de facto to avoid code style or file system mismatch, e.g. different indentations from project maintainers with their custom settings or line endings from unix/windows users.

**Comment by ImagicTheCat** [comment]
I see, I don't approve this to the remote repository, it's more a local working repository specific config stuff. Code conventions for pull requests are not actually written in the doc, but I think they should be written here if necessary instead of relying on a specific file/format in the repository.

**Comment by mbarzda** [comment]
yes, probably such frameworks or libraries like symfony, react uses it for local working :D

**Comment by tabarra** [comment]
Well, that went as expected...  
If @ImagicTheCat is not willing to accept even the most simple no-brainers pull requests, this `.editorconfig` really isn't necessary.

**Comment by ImagicTheCat** [comment]
You could say that I'm obsessed by consistency, but not that I don't accept pull requests.
Anyway you're not the first to be frustrated by my behavior, here is a link to avoid redundancy: https://forum.fivem.net/t/release-vrp-framework/22894/1138

**Pull request closed without merging**
