### PR TITLE
fix deprecated func

### PR DESCRIPTION
**Pull request by SnaiCrys**
https://github.com/ImagicTheCat/vRP/issues/399 https://github.com/ImagicTheCat/vRP/issues/420

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
The deprecated errors are not really errors, the call should not be modified because smoothing was not my intent in the first place. 
What about the panner/listener coords stuff ? Is that standard ? I don't find anything about it.

**Comment by SnaiCrys** [comment]
`value` is no longer used in AudioParam, everywhere it should be replaced with `setTargetAtTime` or `setValueAtTime`. Example: https://github.com/goldfire/howler.js/blob/master/src/plugins/howler.spatial.js

in d6984f4 I forgot to change the coordinate axes and fixed it

**Comment by ImagicTheCat** [comment]
Smoothing is deprecated, it doesn't seem that the value parameter is. Also:
`What about the panner/listener coords stuff ? Is that standard ? I don't find anything about it.`

**Comment by SnaiCrys** [comment]
https://webaudio.github.io/web-audio-api/#dom-audioparam-value

**Pull request closed without merging**
