### PR TITLE
Fix #357

### LINKED ISSUE #357: money cheat number overflow

### PR DESCRIPTION
**Pull request by Sighmir**

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Why clamping ?

**Comment by Sighmir** [comment]
Clamping.. you mean why I wrote it in one line ? .. I am not sure.. I didn't really think it mattered... I actually think that you fix in the money.lua might be better than the one I suggested here, but I only got to see it after I made this pull request. I figured I'd leave the request here in case you thought it would help too.

**Comment by ImagicTheCat** [comment]
You limited the buy ammo to 250, it's not really a fix and is not wanted. What about someone buying 251 ammos ? I'm not sure if my last commit fixed the cheat, but it should (it was probably about negative values from an int overflow, normally lua store floating point number but it seems that it's not the case with fxserver).

**Comment by Sighmir** [comment]
Agreed!

**Pull request closed without merging**
